import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React from 'react'
import axios from 'axios';

export default class Home extends React.Component {
  constructor( props ) {
    super( props );
    this.state = {
      cityName: "",
      url: "",
      responseCode: null,
      weather: "",
      error: "",
    };
    this.handleInput = this.handleInput.bind( this );
    this.fetchWeather = this.fetchWeather.bind( this );
  }

  handleInput( event ) {
    const city = event.target.value;
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${ city }&units=metric&appid=${ process.env.NEXT_PUBLIC_WEATHER_API_KEY }&lang=ja`;
    this.setState( { cityName: city, url: url, } );
  }

  fetchWeather() {
    axios.get( this.state.url )
      .then( res => {
        const resCode = res.status;
        const weather = res.data.weather[ 0 ].description;
        this.setState( { responseCode: resCode, weather: weather, } );
      } )
      .catch( err => {
        console.log( err );
        this.setState( { error: err.message, } );
      } );
  }

  render() {
    return (
      <>
        <Head>
          <title>Broadcast App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>今日の天気を調べてみよう！</h1>
          <form>
            <input name="city" onChange={ this.handleInput } value={ this.state.city } />
            <p>地域：{ this.state.cityName }</p>
            <p>URL：{ this.state.url }</p>
            <button type="button" onClick={ this.fetchWeather }>Check weather!</button>
            <p>レスポンス：{ this.state.responseCode }</p>
            <p>天気：{ this.state.weather }</p>
            <p className={ styles.error }>エラー：{ this.state.error }</p>
          </form>
        </main>
      </>
    );
  }
}
